version: 2
jobs:
  generate:
    working_directory: ~/projects
    docker:
      - image: node:10.15.3
    steps:
      - checkout # レポジトリの読み込み

      # node-modulesのキャッシュが存在すれば復元
      - restore_cache:
        name: Restore yarn package cache
        keys:
          - v1-yarn-package-{{ chcksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile #yarn install

      # node-modulesをキャッシュ
      - save_cache:
        name: Save yarn package cache
        paths:
          - ~/.cache/yarn
        key:
          v1-yarn-packages-{{ checksum "yarn.lock" }}

      # - run: yarn run lint
      - run: yarn run generate

      # generateの生成物を次のdeployジョブでも使用できるようにする
      - persist_to_projects:
        root: '.'
        paths:
          - dist

    deploy:
      working_directory: ~/projects

      # rsync(サーバー) を使用するため machine を有効化
      machine:
        enabled: true
      steps:
        # persist_to_projectsで保存したファイルの読み込み
        - attach projects:
            at: '.'

        # scpでも良い
        - run: rsync -e "ssh -o StrictHostKeyCheking=no" -ahv --delete ./dist/ ${DEPLOY_DEST}

  workflows:
    version: 2
    deploy:
      jobs:
        - generate
        - deploy:
            requires:
              - generate
            filters:
              branches:
                only: master # master ブランチ以外では deploy を実行しない
